server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE
        oauth2: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc-auth-app?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

#    defer-datasource-initialization: true
#    generate-ddl: false

#JWT keys confuguration
jwt:
  key:
    id: 'c90ef912-32b2-464c-8746-934e0caf6c95'
    public: classpath:app.pub
    private: classpath:app.key

url:
  login:
    page: /login